export {HeroSection} from './HeroSection'
export {SocialProofSection} from './SocialProofSection'
export {FeaturesSection} from './FeaturesSection'
export {HowItWorksSection} from './HowItWorksSection'
export {IntegrationsSection} from './IntegrationsSection'
export {TestimonialsSection} from './TestimonialsSection'
export {FAQSection} from './FAQSection'
export {FinalCTASection} from './FinalCTASection'
